name: Deploy PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/CV.pdf
          cp ./pages/index.html ./out/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: CV
          path: out/CV.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: out
