name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/CV.pdf
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./out/CV.pdf